### ISSUE TITLE
Runing environment on SM_86 GPU Architecture Ampere

### ISSUE THREAD

**Issue by hotnikq** [yuval-alaluf/stylegan3-editing#12]
when using a newer graphics card （ like nvidia. GeForce RTX 3090） because the architecture of the graphics card is relatively new ， maybe the older version of the pytorch library does not support the 。 that's when it will show up. capability sm_86 is not compatible at the same time, according to the output, you can see The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 currently, pytorch can only support the above architectures.

**Comment by yuval-alaluf** [comment]
It seems like you need to upgrade your PyTorch version to be compatible with the CUDA version of the 3090 GPU. There are numerous forums on the PyTorch website like [this one](https://discuss.pytorch.org/t/need-help-trouble-with-cuda-capability-sm-86/120235/13) which can help you out.

**Comment by hotnikq** [comment]
the return is:
RuntimeError: CUDA error: no kernel image is available for execution on the device
today I will work around environment for SM_86

**Comment by hotnikq** [comment]
name: sg3_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=hc9558a2_0
  - openssl=1.1.1g=h516909a_0
  - pip=20.0.2=py36_3
  - python=3.6.7=h0371630_0
  - python_abi=3.6=1_cp36m
  - readline=7.0=h7b6447c_5
  - setuptools=46.4.0=py36_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - scipy==1.4.1
    - matplotlib==3.2.1
    - tqdm==4.46.0
    - numpy==1.18.4
    - opencv-python==4.2.0.34
    - pillow==7.1.2
    - tensorboard==2.2.1
    - scikit-learn==0.24.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - dataclasses==0.8
    - dlib==19.22.1
    - ftfy==6.0.3
    - gdown==4.2.0
    - git+https://github.com/openai/CLIP.git
    - pyrallis==0.2.2
prefix: ~/anaconda3/envs/sg3_env

**Comment by hotnikq** [comment]
conda env create -f environment/sg3_env.yaml
conda activate sg3_env
pip install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision==0.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by hotnikq** [comment]
Tested with CUDA111 CUDA112 CUDA113 CUDA115

**Comment by yuval-alaluf** [comment]
Just to verify, this solved your issue with running on the SM_86 architecture?

**Comment by hotnikq** [comment]
its solve, just to
run compute_landmarks_transforms.py
i need to 
pip install cmake
pip install dlib

**Comment by yuval-alaluf** [comment]
Cool. Thanks for the info! 
Closing for now :)
