### ISSUE TITLE
Can I run the repo without GPU?

### ISSUE THREAD

**Issue by zydjohnHotmail** [yuval-alaluf/stylegan3-editing#13]
Hello:
I want to use the repo to generate some images.  However, my PC has NVIDIA Geforce gt 1030 graphic card. This graphic card has no ability to run any CUDA operation, but installing CUDA package is OK.  But my PC has 32-core CPU with 256GB RAM, so I think CPU is powerful enough to do almost all the jobs.
I don't want to train any model, I just want to use pre-trained (.PT) models to generate some human faces or animal images.
Let me know in which python file, I can change so that the image predition use only CPU not GPU.
Thanks,

**Comment by hotnikq** [comment]
you can start with a 3060 12gb
https://github.com/NVlabs/stylegan3#requirements
https://github.com/yuval-alaluf/stylegan3-editing/issues/12

**Comment by woctezuma** [comment]
> CPU may be possible with some modifications, but is not inherently supported.

Reference: https://github.com/yuval-alaluf/stylegan3-editing#prerequisites

**Comment by Part-Work** [comment]
> Hello: I want to use the repo to generate some images. However, my PC has NVIDIA Geforce gt 1030 graphic card. This graphic card has no ability to run any CUDA operation, but installing CUDA package is OK. But my PC has 32-core CPU with 256GB RAM, so I think CPU is powerful enough to do almost all the jobs. I don't want to train any model, I just want to use pre-trained (.PT) models to generate some human faces or animal images. Let me know in which python file, I can change so that the image predition use only CPU not GPU. Thanks,

how did you solve this issue?? I have same problem and I want to run only on CPU, not GPU
