### ISSUE TITLE
pkl to pt conversion

### ISSUE THREAD

**Issue by vedantdere** [yuval-alaluf/stylegan3-editing#16]
How to convert pkl file to pt ?

**Comment by woctezuma** [comment]
https://github.com/yuval-alaluf/stylegan3-editing/blob/e2a63fc7f072c4f8b8a7ba1dac8c7f87a8eb1647/models/stylegan3/legacy.py#L300-L301

**Comment by hotnikq** [comment]
`
python legacy.py \
--source=pretrained_models/stylegan3-r-ffhqu-256x256.pkl \
--dest=pretrained_models/stylegan3-r-ffhqu-256x256.pt
`
Converted to PT File
`
python inversion/scripts/train_restyle_psp.py \
--stylegan_weights pretrained_models/stylegan3-r-ffhqu-256x256.pt
`
raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

**Comment by woctezuma** [comment]
The function does not support StyleGAN3 checkpoints, I believe.

https://github.com/yuval-alaluf/stylegan3-editing/blob/e2a63fc7f072c4f8b8a7ba1dac8c7f87a8eb1647/models/stylegan3/legacy.py#L303-L304

**Comment by hotnikq** [comment]
> The function does not support StyleGAN3 checkpoints, I believe.
How did you create the weights .PT Files For StyleGan3?
https://github.com/yuval-alaluf/stylegan3-editing#stylegan3-encoder

**Comment by yuval-alaluf** [comment]
I believe this is what you guys want: 
```python
path = "/path/to/your/sg3.pkl"

with open(path, "rb") as f:
    decoder = pickle.load(f)['G_ema'].cuda()

state_dict = decoder.state_dict()
torch.save(state_dict, "/path/to/your/sg3.pt") 
```

Let me know if this works as I haven't tested it out yet

**Comment by hotnikq** [comment]
/stylegan3-editing/models/stylegan3/model.py
Line 24 
- `if str(checkpoint_path).endswith("pkl"):`
- `with open(checkpoint_path, "rb") as f:`
- `self.decoder = pickle.load(f)['G_ema'].cuda()`
Replace `https://github.com/yuval-alaluf/stylegan3-editing/issues/16#issuecomment-1101533474`

**Comment by hotnikq** [comment]
return forward_call(*input, **kwargs)
File "<string>", line 210, in forward
RuntimeError: batch1 dim 2 must match batch2 dim 1

i think Stylegan3-editing Receive the .pkl ffhq input
but you cant use the ffhqu ´unaligned´

**Comment by yuval-alaluf** [comment]
@hotnikq , I'm not sure I follow here. 
Please open a new issue if you are having a problem running something. And please provide a clear, detailed summary of what you're trying to run.

**Comment by hotnikq** [comment]
@yuval-alaluf i'm trying to input resized files for stylegan3-editing
i found stylegan3-r-ffhqu-256x256.pkl
@vedantdere ask for .pkl to .pt conversion and i try to apply that with resized files

**Comment by yuval-alaluf** [comment]
@hotnikq , you're saying the code I posted above did not work for you on the `stylegan3-r-ffhqu-256x256.pkl` file?

**Comment by hotnikq** [comment]
@yuval-alaluf 
return forward_call(*input, **kwargs)
File "<string>", line 210, in forward
RuntimeError: batch1 dim 2 must match batch2 dim 1

**Comment by hotnikq** [comment]
its looks like an error for aligned or unaligned files

**Comment by hotnikq** [comment]
@vedantdere 

> How to convert pkl file to pt ?

You can use .pkl files as input and generate a pt file without any modifications

**Comment by hotnikq** [comment]
if i try 
`python legacy.py \`
`--source=pretrained_models/stylegan3-r-ffhq-1024x1024.pkl \`
`--dest=pretrained_models/stylegan3-r-ffhq-1024x1024.pt \`
`--force-fp16=False`
it return 
raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

**Comment by hotnikq** [comment]
How did you create the weights **.PT** Files For **StyleGan3**?
https://github.com/yuval-alaluf/stylegan3-editing#stylegan3-encoder
`i will test rosinality pkl to pt`
and [[dvschultz](https://github.com/dvschultz) [Created using Colaboratory](https://github.com/dvschultz/stylegan2-ada-pytorch/commit/e36e969589df73c5e838413e2ead762cf8250078)](https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/SG2_ADA_PT_to_Rosinality.ipynb)

**Comment by yuval-alaluf** [comment]
> How did you create the weights .PT Files For StyleGan3?

I have answered the question above and provided the code that we used to convert `pkl` files to `pt` files.  I am really not sure why you are still trying to use the `legacy.py` file after it was noted above that this file is not relevant for SG3 models. 
And @hotnikq , it is quite difficult to follow these threads with so many comments. Please try to limit your comments when possible to make it easier for myself and others to follow these threads.

**Comment by hotnikq** [comment]
> I believe this is what you guys want:
> 
> ```python
> path = "/path/to/your/sg3.pkl"
> 
> with open(path, "rb") as f:
>     decoder = pickle.load(f)['G_ema'].cuda()
> 
> state_dict = decoder.state_dict()
> torch.save(state_dict, "/path/to/your/sg3.pt") 
> ```
> 
> Let me know if this works as I haven't tested it out yet

Testing now !

**Comment by hotnikq** [comment]
import pickle
from enum import Enum
from pathlib import Path
from typing import Optional

import torch

checkpoint_path = "pretrained_models/stylegan3-r-ffhqu-256x256.pkl"

print(f"Loading StyleGAN3 generator from path: {checkpoint_path}")
with open(checkpoint_path, "rb") as f:
	decoder = pickle.load(f)['G_ema'].cuda()
print('Done!')
       
state_dict = decoder.state_dict()
torch.save(state_dict, "pretrained_models/stylegan3-r-ffhqu-256x256.pt")

print('Done!')

**Comment by yuval-alaluf** [comment]
I am happy to see that the code I gave you above works fine and that we can now close this issue. 
If you have an issue that is unrelated to this, please open a new issue with a concise yet clear explanation of the problem you are facing
