### ISSUE TITLE
Whether this project can be applied to other data sets like shoes

### ISSUE THREAD

**Issue by ww451575464** [yuval-alaluf/stylegan3-editing#21]
hello, My team collected a lot of pictures of shoes，and we want to know if this project can help us generate more shoes。
thanks you ！

**Comment by yuval-alaluf** [comment]
It seems like what you want is to original StyleGAN3 repository here: https://github.com/NVlabs/stylegan3
You can use that repo to train a generator to generate new images of shoes. If you would like,  you can then use this repo to edit those images, for example.

**Comment by ww451575464** [comment]
thank you !
But my picture is unaligned and have no landmarks, I want to use this project to edit the generated picture

**Comment by yuval-alaluf** [comment]
You don't need aligned data or landmarks to train the StyleGAN3 generator. Once you train the generator on your data, you can then use this repo for editing.
