### ISSUE TITLE
encoder_bootstrapping_inference for SG3

### ISSUE THREAD

**Issue by hqnicolas** [yuval-alaluf/stylegan3-editing#22]
hello,
I missed the encoder_bootstrapping_inference in this sg3 application I don't know if it's in the standard you work with, but for anyone interested it should work
 I tried to publish a code that I've been working on Computing landmarks transforms multithreading on CPU but my account is blocked [Hotnikq on github](https://github.com/hotnikq)

[/stylegan3-editing/encoder_bootstrapping_inference.py](https://drive.google.com/file/d/1AuDHbywa25avwPe8HCQDsmXQq_g2YVbU/view?usp=sharing)
[/stylegan3-editing/utils/bootstrap_utils.py](https://drive.google.com/file/d/1XDGVhTUKXiOZTL1A_FM-c7iNXGva2NwA/view?usp=sharing)
[/stylegan3-editing/inversion/models/psp32.py](https://drive.google.com/file/d/1LBTqm8hPB5VGdAftqLYlIrxtLp9glsFx/view?usp=sharing)
[/stylegan3-editing/inversion/options/train_options.py](https://drive.google.com/file/d/1OThYvKGWeUb3FrrrosbdgRQY3TrHajAK/view?usp=sharing)
[/stylegan3-editing/inversion/options/test_options.py](https://drive.google.com/file/d/1SOsHi8VKARq9g0FIoe_ckSFeHgSOT8Y4/view?usp=sharing)

```
python encoder_bootstrapping_inference.py \
--output_path experiments \
--checkpoint_path pretrained_models/sg3_ffhq_256.pt \
--checkpoint_path2 pretrained_models/sg3_toonify_256.pt \
--data_path ffhq \
--test_batch_size=4 \
--test_workers=8 \
--resize_outputs=256\
--n_iters_per_batch=4
```

**Comment by yuval-alaluf** [comment]
@hqnicolas Since this is not an issue with this repository, I recommend creating a fork of this repository and making all your changes there. You can make all the changes you want there independent of this repository. Thanks

**Comment by hqnicolas** [comment]
Please unblock the [Hotnikq on github](https://github.com/hotnikq) account so that I can make the codes available to those who are interested in running these functions
