### ISSUE TITLE
Edit generated images which trained by stylegan2-ada-pytorch

### ISSUE THREAD

**Issue by 49xxy** [yuval-alaluf/stylegan3-editing#31]
Hi！Thank you for a job well done！
I want to use Styleclip to edit my trained models. What should I do？

**Comment by yuval-alaluf** [comment]
This repo is designed for StyleGAN3. If you want to use StyleGAN2, it is best to use the official StyleCLIP repo.

**Comment by ikcla** [comment]
use the same parameter in environment/sg3_env as conda env create -f, but I got error when inference

python inversion/scripts/inference_iterative.py --output_path experiments/restyle_e4e_ffhq_encode/inference --checkpoint_path pretrained_models/restyle_e4e_ffhq.pt --data_path /usr/src/myapp/stylegan3-editing/ --test_batch_size 4 --test_workers 1 --n_iters_per_batch 3 --landmarks_transforms_path output/landmarks_transforms.npy
Loading ReStyle e4e from checkpoint: pretrained_models/restyle_e4e_ffhq.pt
Loading StyleGAN3 generator from path: None
Done!
Model successfully loaded!
Loading dataset for ffhq_encode
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
0it [00:00, ?it/s]
/opt/conda/envs/sg3_env/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/conda/envs/sg3_env/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/opt/conda/envs/sg3_env/lib/python3.6/site-packages/numpy/core/_methods.py:234: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/opt/conda/envs/sg3_env/lib/python3.6/site-packages/numpy/core/_methods.py:195: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/opt/conda/envs/sg3_env/lib/python3.6/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Runtime nan+-nan

Any ideas how to fix it?
