### ISSUE TITLE
Some thing weird with FFHQ-00000.png

### ISSUE THREAD

**Issue by zhongtao93** [yuval-alaluf/stylegan3-editing#33]
Hi, thank you for sharing source code!
I test 00000.png in FFHQ dataset, but it seems not very well.
![image](https://user-images.githubusercontent.com/15263824/176842956-2d6180c4-0d29-4484-98dc-07522b382469.png)
I get this results by cmd below：
`python inversion/scripts/inference_editing.py \
--output_path /DATA/jupyter/tmp_data/FFHQ-1024x1024-beyoung/ \
--checkpoint_path pretrained_models/restyle_e4e_ffhq.pt \
--data_path /DATA/jupyter/tmp_data/FFHQ-1024x1024/ \
--test_batch_size 4 \
--test_workers 4 \
--n_iters_per_batch 3 \
--edit_directions "[age]" \
--factor_ranges "[(-5_5)]" `

Hope for your reply~

**Comment by yuval-alaluf** [comment]
Does your `--output_path` point to the directory where your inference results were saved to?

**Comment by zhongtao93** [comment]
Yes.
But it seems to be a special case. I tested dozens of other FFHQ pictures, but this didn't happen
