### ISSUE TITLE
The reconstructed image is strange

### ISSUE THREAD

**Issue by ZziTaiLeo** [yuval-alaluf/stylegan3-editing#36]
When I tried to use the PTI optimization model and run the inference_on_Videos. py file, the adhesion effect of the video result was too obvious, like pulling gum. In a single frame of the picture, this effect could be reflected in the afro, and the viscous effect in the two frames of the afro could be seen, which was very average in the video performance. This phenomenon also exists in reconstructed video.

The image below shows the original, reconstructed, and edited afro.
![00437](https://user-images.githubusercontent.com/42994566/180422043-e4d02b06-1d6e-4b1e-b271-c17bd3256511.jpg)

**Comment by yuval-alaluf** [comment]
I have a feeling that there is something wrong with the inversion since the reconstruction is quite poor, perhaps leading to the poor editing you got on the right. 
If you did everything correctly, you should be able to get a very good reconstruction of the original video.
