### ISSUE TITLE
edit beard failed by styleclip

### ISSUE THREAD

**Issue by onefish51** [yuval-alaluf/stylegan3-editing#4]
I edited beard  by  styleclip 
```
--neutral_text "face" \
--target_tex "face with beard" \
```

but  I failed ! the outputs :
![pexels-photo-8554246](https://user-images.githubusercontent.com/21029719/155977814-3c6f799e-59cf-48c9-9175-6e27fc3ceba8.jpg)

and I edit age by `--neutral_text "a face" --target_tex "a old face" ` failed ,but I used `--neutral_text "a young face" --target_tex "a old face" ` work

**Comment by yuval-alaluf** [comment]
We also saw that some edits that worked on SG2 did not work well on SG3, including beard and hair color. 
It could be that some modifications to StyleCLIP could help adapt it to SG3.

**Comment by onefish51** [comment]
OK
