### ISSUE TITLE
Dirty result image

### ISSUE THREAD

**Issue by shartoo** [yuval-alaluf/stylegan3-editing#49]
Running  `run_on_batch` in  `utils/inference_utils.py` with hyper parameter `n_iters=3` and `restyle_pSp_ffhq`, the rebuild images seem dirty compared with original image.What can i do to avoid such result?

+ original images
![image](https://github.com/yuval-alaluf/stylegan3-editing/assets/5716282/00914a13-4457-4f2a-a4ae-63b434d939f1)
+ rebuild images 
![image](https://github.com/yuval-alaluf/stylegan3-editing/assets/5716282/13752af5-7150-49d8-8257-7f4eb5d12347)

**Comment by YKJamesMoriarty** [comment]
hi,how did you overcome this problem,i have the same dirty result too,please give me some help~thanks!
